const trackingState = {
  DELIVERED: "DELIVERED",
  DELIVERED_TO_SENDER: "DELIVERED_TO_SENDER",
  TICKET_CREATED: "TICKET_CREATED",
  PACKAGE_RECEIVED: "PACKAGE_RECEIVED",
  NOT_YET_SHIPPED: "NOT_YET_SHIPPED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  WAITING_FOR_CUSTOMER_ACTION: "WAITING_FOR_CUSTOMER_ACTION",
  IN_TRANSIT: "IN_TRANSIT",
};

export default trackingState;
